controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - joint_8
      - joint_9
      - joint_10
      - joint_11
      - joint_12

    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"] 
    interpolation_method: splines
    allow_partial_joints_goal: true
    open_loop_control: false

    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.01
      
      joint_1:
        trajectory: 0.5
        goal: 0.1
      joint_2:
        trajectory: 0.5
        goal: 0.1
      joint_3:
        trajectory: 0.5
        goal: 0.1
      joint_4:
        trajectory: 0.5
        goal: 0.1
      joint_5:
        trajectory: 0.5
        goal: 0.1
      joint_6:
        trajectory: 0.5
        goal: 0.1
      joint_7:
        trajectory: 0.5
        goal: 0.1
      joint_8:
        trajectory: 0.5
        goal: 0.1
      joint_9:  
        trajectory: 0.5
        goal: 0.1
      joint_10:
        trajectory: 0.5
        goal: 0.1
      joint_11:
        trajectory: 0.5
        goal: 0.1
      joint_12:
        trajectory: 0.5
        goal: 0.1
    
    action_monitor_rate: 20.0
